development:
  clients:
    default:
      uri: <%= ENV.fetch("MONGODB_URI") { "mongodb://localhost:27017/savant_development" } %>
      options:
        server_selection_timeout: 1

test:
  clients:
    default:
      uri: <%= ENV.fetch("MONGODB_URI") { "mongodb://localhost:27017/savant_test" } %>
      options:
        server_selection_timeout: 1
